name: bloom
description: "Bloom"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.1.3

  #Architecture
  flutter_bloc: ^8.1.6

  # Dependency injection
  get_it: ^7.7.0
  injectable: ^2.4.4

  # Navigation
  go_router: ^14.1.4

  # Networking
  #http: ^1.0.0
  dio: ^5.2.1+1
  retrofit: ^4.4.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.5

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # Utils
  equatable: ^2.0.5
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

  # UI Kit
  app_ui_kit:
    path: packages/app_ui_kit
  dots_indicator: ^3.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  rxdart: ^0.28.0
  flutter_svg: ^2.0.14
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/onboarding/
    - assets/svg/

flutter_intl:
  enabled: true
