include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    invalid_annotation_target: warning #change tags to 'error' later
    invalid_use_of_protected_member: warning #error
    always_use_package_imports: warning #error
    avoid_empty_else: warning #error
    avoid_relative_lib_imports: warning #error
    cancel_subscriptions: warning #error
    close_sinks: warning #error
    no_duplicate_case_values: warning #error
    throw_in_finally: warning #error
    always_declare_return_types: warning
    always_put_required_named_parameters_first: warning
    annotate_overrides: warning #error
    avoid_catches_without_on_clauses: warning #error
    avoid_catching_errors: warning #error
    avoid_unnecessary_containers: warning
    directives_ordering: warning
    empty_catches: warning
    empty_constructor_bodies: warning
    only_throw_errors: warning #error
    prefer_final_fields: warning
    prefer_final_in_for_each: warning
    prefer_final_locals: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_iterable_whereType: warning
    prefer_mixin: warning
    prefer_null_aware_method_calls: warning
    prefer_null_aware_operators: warning
    recursive_getters: warning #error
    require_trailing_commas: warning
    sized_box_for_whitespace: warning
    sized_box_shrink_expand: warning
    sort_child_properties_last: warning
    sort_constructors_first: warning
    sort_unnamed_constructors_first: warning
    type_annotate_public_apis: warning
    unawaited_futures: warning
    use_colored_box: warning
    use_decorated_box: warning
    use_enums: warning
    use_is_even_rather_than_modulo: warning
    use_named_constants: warning
    use_super_parameters: warning
    unnecessary_this: warning
    prefer_const_constructors: warning
    avoid_function_literals_in_foreach_calls: ignore
    constant_identifier_names: ignore
    avoid_renaming_method_parameters: warning
    await_only_futures: warning
    prefer_adjacent_string_concatenation: warning
    prefer_const_literals_to_create_immutables: warning
    unnecessary_new: warning
    prefer_collection_literals: warning
    curly_braces_in_flow_control_structures: warning
    non_constant_identifier_names: warning
    avoid_types_as_parameter_names: warning
    prefer_const_declarations: warning
    unnecessary_const: warning
    use_key_in_widget_constructors: warning
    body_might_complete_normally_nullable: warning
    override_on_non_overriding_member: warning
    unnecessary_brace_in_string_interps: warning
    use_function_type_syntax_for_parameters: warning
    avoid_bool_literals_in_conditional_expressions: ignore
    unrelated_type_equality_checks: error
    prefer_typing_uninitialized_variables: warning
    avoid_return_types_on_setters: warning
    prefer_function_declarations_over_variables: warning
    library_prefixes: warning
    unnecessary_string_interpolations: warning
    file_names: warning
    prefer_const_constructors_in_immutables: warning
    unnecessary_import: warning
    unnecessary_null_comparison: warning
    overridden_fields: warning
    unused_import: warning
    dead_code: warning
    unused_element: warning
    deprecated_member_use: warning

  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.config.dart

linter:
  rules:
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    empty_catches: true
    no_duplicate_case_values: true
    throw_in_finally: true
    empty_constructor_bodies: true
    prefer_final_in_for_each: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    recursive_getters: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    type_annotate_public_apis: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_super_parameters: true
    unnecessary_this: true
    prefer_const_constructors: true

    #############

    use_build_context_synchronously: true
    directives_ordering: true
    prefer_final_fields: true
    comment_references: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    always_put_control_body_on_new_line: true
    omit_local_variable_types: true
    prefer_constructors_over_static_methods: true
    prefer_final_locals: true
    only_throw_errors: true
    prefer_relative_imports: false
    non_constant_identifier_names: true
    avoid_returning_this: true
    avoid_catching_errors: true
    constant_identifier_names: true
    prefer_function_declarations_over_variables: true
    avoid_classes_with_only_static_members: true
    avoid_function_literals_in_foreach_calls: true
    use_key_in_widget_constructors: true
    prefer_mixin: false #??
    public_member_api_docs: false

    # invalid_runtime_check_with_js_interop_types: true

    prefer_single_quotes: true

    #############

    # Far too verbose, and not that big of a deal when using parameter_assignments
    prefer_final_parameters: false

    # Personal preference. I don't find it more readable
    cascade_invocations: true

    # Conflicts with `prefer_single_quotes`
    # Single quotes are easier to type and don't compromise on readability.
    # prefer_double_quotes: false

    # Conflicts with `omit_local_variable_types` and other rules.
    # As per Dart guidelines, we want to avoid unnecessary types to make the code
    # more readable.
    # See https://dart.dev/guides/language/effective-dart/design#avoid-type-annotating-initialized-local-variables
    always_specify_types: false

    # Incompatible with `prefer_final_locals`
    # Having immutable local variables makes larger functions more predictible
    # so we will use `prefer_final_locals` instead.
    unnecessary_final: false

    # Not quite suitable for Flutter, which may have a `build` method with a single
    # return, but that return is still complex enough that a "body" is worth it.
    prefer_expression_function_bodies: false

    # Conflicts with the convention used by flutter, which puts `Key key`
    # and `@required Widget child` last.
    always_put_required_named_parameters_first: true

    # This project doesn't use Flutter-style todos
    flutter_style_todos: true

    # There are situations where we voluntarily want to catch everything,
    # especially as a library.
    avoid_catches_without_on_clauses: true

    # Boring as it sometimes force a line of 81 characters to be split in two.
    # As long as we try to respect that 80 characters limit, going slightly
    # above is fine.
    lines_longer_than_80_chars: false

    # Conflicts with disabling `implicit-dynamic`
    avoid_annotating_with_dynamic: false

    # conflicts with `prefer_relative_imports`
    always_use_package_imports: true

    # Disabled for now until we have NNBD as it otherwise conflicts with `missing_return`
    no_default_cases: false

    # False positive, null checks don't need a message
    prefer_asserts_with_message: false

    # Cumbersome with `context.select`
    avoid_types_on_closure_parameters: false

    # Too many false positive (builders)
    diagnostic_describe_all_properties: false

    # false positives (setter-like functions)
    avoid_positional_boolean_parameters: false

    # Does not apply to providers
    prefer_const_constructors_in_immutables: false
