name: app_ui_kit
description: App ui kit package

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter_svg: ^2.0.10

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0